<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-23T19:48:57 IST" name="Suite" finished-at="2025-03-23T19:50:04 IST" duration-ms="66519">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.LoginErrorValidation()[pri:0, instance:SA2025.ErrorValidation@5629510]" name="LoginErrorValidation" class="SA2025.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="StandAloneTest.submitOrder(java.util.HashMap)[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" name="submitOrder" class="SA2025.StandAloneTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-03-23T19:48:57 IST" name="Submit Order" finished-at="2025-03-23T19:49:36 IST" duration-ms="38937">
      <class name="SA2025.StandAloneTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:48:58 IST" name="launchApp" finished-at="2025-03-23T19:49:05 IST" duration-ms="7623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:05 IST" name="submitOrder" data-provider="DataProvider" finished-at="2025-03-23T19:49:20 IST" duration-ms="15163" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pass=Vinay@490, email=vinaybubgsit@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:20 IST" name="tearDown" finished-at="2025-03-23T19:49:21 IST" duration-ms="127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:21 IST" name="launchApp" finished-at="2025-03-23T19:49:25 IST" duration-ms="4863" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:25 IST" name="submitOrder" data-provider="DataProvider" finished-at="2025-03-23T19:49:29 IST" duration-ms="3941" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pass=Vinay@490, email=vinaykumarbu@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:29 IST" name="tearDown" finished-at="2025-03-23T19:49:30 IST" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:30 IST" name="launchApp" finished-at="2025-03-23T19:49:35 IST" duration-ms="5317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="orderHistoryTest()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:35 IST" name="orderHistoryTest" finished-at="2025-03-23T19:49:36 IST" depends-on-methods="SA2025.StandAloneTest.submitOrder" duration-ms="1145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SA2025.StandAloneTest@5e4bd84a]" started-at="2025-03-23T19:49:36 IST" name="tearDown" finished-at="2025-03-23T19:49:36 IST" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SA2025.StandAloneTest -->
    </test> <!-- Submit Order -->
    <test started-at="2025-03-23T19:49:37 IST" name="Error validation" finished-at="2025-03-23T19:50:04 IST" duration-ms="26963">
      <class name="SA2025.ErrorValidation">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:37 IST" name="launchApp" finished-at="2025-03-23T19:49:39 IST" duration-ms="2592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:39 IST" name="LoginErrorValidation" finished-at="2025-03-23T19:49:40 IST" duration-ms="649" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or passwordd.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passwordd.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SA2025.ErrorValidation.LoginErrorValidation(ErrorValidation.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:40 IST" name="tearDown" finished-at="2025-03-23T19:49:40 IST" duration-ms="88" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:40 IST" name="launchApp" finished-at="2025-03-23T19:49:44 IST" duration-ms="3839" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:44 IST" name="LoginErrorValidation" finished-at="2025-03-23T19:49:45 IST" duration-ms="607" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or passwordd.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passwordd.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SA2025.ErrorValidation.LoginErrorValidation(ErrorValidation.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:45 IST" name="tearDown" finished-at="2025-03-23T19:49:45 IST" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:45 IST" name="launchApp" finished-at="2025-03-23T19:49:49 IST" duration-ms="4385" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="ProductErrorValidation()[pri:2, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:49:49 IST" name="ProductErrorValidation" finished-at="2025-03-23T19:50:04 IST" duration-ms="14238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SA2025.ErrorValidation@5629510]" started-at="2025-03-23T19:50:04 IST" name="tearDown" finished-at="2025-03-23T19:50:04 IST" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SA2025.ErrorValidation -->
    </test> <!-- Error validation -->
  </suite> <!-- Suite -->
</testng-results>
